# Generated by Django 5.2.17 on 2026-09-30 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('severity', models.CharField(max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('MIXED', 'Mixed')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('duplicate_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('ALLOW', 'Allow'), ('REVIEW', 'Review'), ('BLOCK', 'Block')], default='ALLOW', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feedback.feedback')),
            ],
        ),
    ]
