# Generated by Django 5.2.17 on 2026-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('overview', models.TextField()),
                ('response_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('positive_signals', models.JSONField(blank=True, default=list)),
                ('top_issues', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
